apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tomcat
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
