apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tomcat-service
spec:
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
